import { CatalogueGarment } from './types.js';

export const DEFAULT_CATALOGUE: CatalogueGarment[] = [
  {
    id: 'garment-1',
    sku: 'SKU-SAR-001',
    name: 'Kanjeevaram Crimson Royal Silk Saree',
    nameHi: 'कांचीवरम क्रिमसन रॉयल सिल्क साड़ी',
    nameTe: 'కాంజీవరం రాయల్ సిల్క్ చీర',
    category: 'saree',
    price: 18500,
    size: 'Free Size (5.5m + 0.8m Blouse)',
    fabric: 'Pure Mulberry Silk with 24K Gold Zari',
    color: 'Crimson Red with Antique Gold Pallu',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    description: 'Traditional temple border Kanjeevaram with intricate peacocks motif woven in gold zari and rich contrast pallu with heavy tassels.',
    tryOnCount: 142,
    featured: true,
  },
  {
    id: 'garment-2',
    sku: 'SKU-LEH-002',
    name: 'Emerald Banarasi Handloom Bridal Lehenga',
    nameHi: 'एमराल्ड बनारसी ब्राइडल लहंगा',
    nameTe: 'ఎమరాల్డ్ బనారసి పెళ్లి లెహంగా',
    category: 'lehenga',
    price: 36000,
    size: 'Semi-stitched (Waist 32-42)',
    fabric: 'Katan Silk with Kadwa Weave',
    color: 'Deep Emerald Green & Champagne Gold',
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    description: 'Royal emerald green flared Banarasi lehenga with zari kalis, hand-embroidered velvet blouse and organza scalloped dupatta.',
    tryOnCount: 98,
    featured: true,
  },
  {
    id: 'garment-3',
    sku: 'SKU-KUR-003',
    name: 'Chanderi Silk Ivory Kurta Churidar Set',
    nameHi: 'चंदेरी सिल्क आइवरी कुर्ता चूड़ीदार सेट',
    nameTe: 'చందేరి సిల్క్ కుర్తా చూడిదార్ సెట్',
    category: 'kurta_pajama',
    price: 7800,
    size: 'M, L, XL, XXL',
    fabric: 'Chanderi Silk with Cotton Silk Lining',
    color: 'Ivory & Gold Resham',
    imageUrl: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=800&q=80',
    description: 'Bespoke hand-embroidered mandarin collar kurta with intricate threadwork placket paired with stretch churidar and printed stole.',
    tryOnCount: 76,
    featured: true,
  },
  {
    id: 'garment-4',
    sku: 'SKU-SHR-004',
    name: 'Maharaja Royal Raw Silk Sherwani',
    nameHi: 'महाराजा रॉयल रॉ सिल्क शेरवानी',
    nameTe: 'మహారాజా రాయల్ రా సిల్క్ షేర్వానీ',
    category: 'sherwani',
    price: 42000,
    size: '38, 40, 42, 44',
    fabric: 'Raw Matka Silk with Zardozi Work',
    color: 'Antique Rose Gold & Cream',
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    description: 'Regal achkan sherwani with zardozi collar, metal monogram buttons, coordinated dhoti pants, and handcrafted safa fabric.',
    tryOnCount: 64,
    featured: false,
  },
  {
    id: 'garment-5',
    sku: 'SKU-SAL-005',
    name: 'Kashmiri Tilla Embroidered Salwar Suit',
    nameHi: 'कश्मीरी तिल्ला एम्ब्रॉयडर्ड सलवार सूट',
    nameTe: 'కాశ్మీరీ తిల్లా సల్వార్ సూట్',
    category: 'salwar_suit',
    price: 9400,
    size: 'Unstitched / Free Size',
    fabric: 'Pure Georgette with Silk Dupatta',
    color: 'Midnight Sapphire Blue',
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    description: 'Straight-cut long tunic with exquisite Kashmiri tilla embroidery around yoke and hemline, with flowy palazzo and banarasi dupatta.',
    tryOnCount: 53,
    featured: false,
  },
  {
    id: 'garment-6',
    sku: 'SKU-DRS-006',
    name: 'Midnight Velvet Pleated Evening Gown',
    nameHi: 'मिडनाइट वेलवेट प्लीटेड इवनिंग गाउन',
    nameTe: 'మిడ్‌నైట్ వెల్వెట్ ఈవెనింగ్ గౌన్',
    category: 'dress',
    price: 14500,
    size: 'S, M, L',
    fabric: 'Italian Micro Velvet with Sequin Yoke',
    color: 'Midnight Obsidian Black',
    imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80',
    description: 'Floor-sweeping structured evening gown with sweetheart neckline, subtle thigh slit and hand-applied crystal starry shimmer.',
    tryOnCount: 45,
    featured: false,
  },
  {
    id: 'garment-7',
    sku: 'SKU-SHT-007',
    name: 'Italian Linen Cutaway Shirt & Tailored Trousers',
    nameHi: 'इटैलियन लिनन शर्ट एवं फॉर्मल ट्राउजर',
    nameTe: 'ఇటాలియన్ లినెన్ షర్టు & ట్రౌజర్స్',
    category: 'shirt_trousers',
    price: 6200,
    size: '38, 40, 42 (Waist 30-36)',
    fabric: '100% Normandy Linen & Wool Blend Trousers',
    color: 'Powder Sky Blue & Slate Charcoal',
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    description: 'Breathable European linen shirt with mother-of-pearl buttons and relaxed pleated trousers with brass side-adjusters.',
    tryOnCount: 38,
    featured: false,
  }
];
